---
- name: bootstrap
  hosts: all
  become: yes
  tags: [ bootstrap ]
  roles:
    - bootstrap

- name: nomad
  hosts: all
  become: yes
  roles:
    - community.consul
    - robertdebock.docker
    - geerlingguy.java
    - community.nomad
