- name: geerlingguy.java

- name: community.consul
  src: https://github.com/ansible-community/ansible-consul
  version: e43e2c0

- name: community.nomad
  src: https://github.com/ansible-community/ansible-nomad
  version: v1.9.6
